config/routes.rb
Sample2::Application.routes.draw do
  resources :clusters do 
	collection {post :import}
  end

 root :to => 'clusters#index'

end

app/models/cluster.rb
class Cluster < ActiveRecord::Base
  attr_accessible :cluster, :numcpucores, :totalcpu, :totalmemory, :vcserver
 def self.import(file)
  ::CSV.foreach(file.path, headers: true) do |row|
    cluster = find_by_id(row["id"]) || new
    cluster.attributes = row.to_hash.slice(*accessible_attributes)
    cluster.save!
#  Cluster.create! row.to_hash
  end
 end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/clusters_controller.rb
class ClustersController < ApplicationController
  # GET /clusters
  # GET /clusters.json
  def index
    @clusters = Cluster.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clusters }
    end
  end
def import
  Cluster.import(params[:file])
  redirect_to root_url, notice: "Clusters imported."
end
  # GET /clusters/1
  # GET /clusters/1.json
  def show
    @cluster = Cluster.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cluster }
    end
  end

  # GET /clusters/new
  # GET /clusters/new.json
  def new
    @cluster = Cluster.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cluster }
    end
  end

  # GET /clusters/1/edit
  def edit
    @cluster = Cluster.find(params[:id])
  end

  # POST /clusters
  # POST /clusters.json
  def create
    @cluster = Cluster.new(params[:cluster])

    respond_to do |format|
      if @cluster.save
        format.html { redirect_to @cluster, notice: 'Cluster was successfully created.' }
        format.json { render json: @cluster, status: :created, location: @cluster }
      else
        format.html { render action: "new" }
        format.json { render json: @cluster.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /clusters/1
  # PUT /clusters/1.json
  def update
    @cluster = Cluster.find(params[:id])

    respond_to do |format|
      if @cluster.update_attributes(params[:cluster])
        format.html { redirect_to @cluster, notice: 'Cluster was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cluster.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clusters/1
  # DELETE /clusters/1.json
  def destroy
    @cluster = Cluster.find(params[:id])
    @cluster.destroy

    respond_to do |format|
      format.html { redirect_to clusters_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clusters_helper.rb
module ClustersHelper
end

app/views/clusters/_form.html.erb
<%= form_for(@cluster) do |f| %>
  <% if @cluster.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cluster.errors.count, "error") %> prohibited this cluster from being saved:</h2>

      <ul>
      <% @cluster.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :vcserver %><br />
    <%= f.text_field :vcserver %>
  </div>
  <div class="field">
    <%= f.label :cluster %><br />
    <%= f.text_field :cluster %>
  </div>
  <div class="field">
    <%= f.label :totalcpu %><br />
    <%= f.text_field :totalcpu %>
  </div>
  <div class="field">
    <%= f.label :totalmemory %><br />
    <%= f.text_field :totalmemory %>
  </div>
  <div class="field">
    <%= f.label :numcpucores %><br />
    <%= f.text_field :numcpucores %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clusters/edit.html.erb
<h1>Editing cluster</h1>

<%= render 'form' %>

<%= link_to 'Show', @cluster %> |
<%= link_to 'Back', clusters_path %>

app/views/clusters/index.html.erb
<h1>Listing clusters</h1>

<table>
  <tr>
    <th>Vcserver</th>
    <th>Cluster</th>
    <th>Totalcpu</th>
    <th>Totalmemory</th>
    <th>Numcpucores</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @clusters.each do |cluster| %>
  <tr>
    <td><%= cluster.vcserver %></td>
    <td><%= cluster.cluster %></td>
    <td><%= cluster.totalcpu %></td>
    <td><%= cluster.totalmemory %></td>
    <td><%= cluster.numcpucores %></td>
    <td><%= link_to 'Show', cluster %></td>
    <td><%= link_to 'Edit', edit_cluster_path(cluster) %></td>
    <td><%= link_to 'Destroy', cluster, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />
<h2>Import Products</h2>
<%= form_tag import_clusters_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>
<%= link_to 'New Cluster', new_cluster_path %>

app/views/clusters/new.html.erb
<h1>New cluster</h1>

<%= render 'form' %>

<%= link_to 'Back', clusters_path %>

app/views/clusters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Vcserver:</b>
  <%= @cluster.vcserver %>
</p>

<p>
  <b>Cluster:</b>
  <%= @cluster.cluster %>
</p>

<p>
  <b>Totalcpu:</b>
  <%= @cluster.totalcpu %>
</p>

<p>
  <b>Totalmemory:</b>
  <%= @cluster.totalmemory %>
</p>

<p>
  <b>Numcpucores:</b>
  <%= @cluster.numcpucores %>
</p>


<%= link_to 'Edit', edit_cluster_path(@cluster) %> |
<%= link_to 'Back', clusters_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sample2</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>